#!/usr/bin/bash
mkdir build
for i in wdw.gc.aux wdw.gc GCsolve; do g++ -Wall -std=c++17 -O3 -c -o build/$i.o src/$i.cpp -fopenmp; done
cd build
g++ -Wall -std=c++17 -O3 -o wdw.gc wdw.gc.aux.o wdw.gc.o GCsolve.o -fopenmp
