# ==============================================================================
# Wheeler-DeWitt Solver (wdw.gc) - Configuration File
# ==============================================================================
# GENERAL RULES:
# - Lines starting with ’#’ and blank lines are ignored.
# - Variables are CASE SENSITIVE.
# - Format required: <VariableName> <Value>
# - Unrecognized or unused variables are safely ignored.
# ==============================================================================

# --- Hardware / Parallelism ---
# NProc     40      # Uncomment to manually set OpenMP threads
# (defaults to max available)

# --- Grid Discretization (Crank-Nicoslon) ---
Na        6000          # Number of grid points for the scale factor 'a'
Nphi      9000          # Number of grid points for the scalar field 'phi'
a         20            # Maximum boundary value for the scale factor grid
phi       40            # Maximum boundary value for the scalar field grid
# R         3           # Order aproximation for second diferentiation on a and phi, defaults to 1

# --- Effective Potential (Vef) ---
Lambda    1.5           # Cosmological constant parameter
m         0.1           # Mass of the scalar field
aVmax     1.0           # Cutoff or maximum limit for the potential

# --- Initial Wave Function (Psi0) ---
Ea        5.498         # Initial energy/momentum parameter for 'a'
Ephi      4.0           # Initial energy/momentum parameter for 'phi'

# --- Conjnugate Gradient (CG) Solver ---
Imax      500           # Maximum number of CG iterations per time step
Emax      1e-8          # Error tolerance for CG convergence

# --- Time evolution ---
Tlast     1.0           # Final time for the evolution
T         1.0           # Grid definition for time evolution Nt = T/DeltaT
DeltaT    0.00001       # Time step size for the evolution
Print     2500          # Print/Save Checkpoints every 'Print' iterations

# --- Checkpoints & Output Data ---
Resume    false         # Set to 'true' to resume from a preveious checkpoint
rest      0.755         # Time point of the restored state (if Resume is true)
resfile a5phi4_00.755   # Name of the checkpoint file to load for resume computing
file a10phi9_           # Prefix for generated output files
BaseDir lbd1.5/m0.1/a10phi9 # Base directory to seve output data
